services:
  echo_server:
    image: doublehub/echo_demo:a00b69f
    # image: echo_demo
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - "8080:8080/udp"
    command: /app/echo_server 8080

  echo_client:
    image: doublehub/echo_demo:a00b69f
    # image: echo_demo
    depends_on:
      - echo_server
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    command: /app/echo_client echo_server 8080 "Hello Echo Server"